sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1
services:
  - postgresql

before_install: gem install bundler -v 1.12.5

before_script:
  - "cd spec/support/rails_app"
  - "cp config/database.yml.sample config/database.yml"
  - "sed -i '/host*/d' config/database.yml && sed -i '/username*/d' config/database.yml && sed -i '/password*/d' config/database.yml"
  - "bundle install"
  - "cd ../../.."

script:
  - "bundle exec rake spec"
  - "RAILS_ENV=test CODECLIMATE_REPO_TOKEN=1bf37ecba56ffa95ff329cbbc3c3edc31c0ba9145baa929b8a56fff778b8c952 bundle exec codeclimate-test-reporter"
