version: '2'

services:
  postgres:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      POSTGRES_DB: 'central_support_test'

  app:
    build: .
    volumes:
      - .:/app
    links:
      - postgres
    command: bash -c "echo \"Container Started\" && tail -f /dev/null"

volumes:
  db: