# PostgreSQL
development:
  adapter: postgresql
  encoding: unicode
  database: central_support_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: central_support_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: central_support_production
  pool: 5
